### ISSUE TITLE
Data directory?

### ISSUE THREAD

**Issue by steve-kasica** [striblab/201901-achievementgap#1]
Is the data for this repository publically available?

**Comment by mjwebster** [comment]
I'm not going to share what I have because it is so immensely flawed. We had a horrible time getting accurate data from the Dept of Education that we ended up having to piece together different chunks to get what we needed. Your best bet is to request the data you specifically want from the Minnesota Department of Education. It is public data available to anyone.

**Comment by steve-kasica** [comment]
Ok thank you
